- stts/Services/Docker.swift
- stts/Services/Super/Service.swift
First things first: AWESOME little app, THX for OSSing @inket ! 👍 
About the PR: For the time being, just a dedicated, extra service... thought about wrapping into `Super/StatusioService`... either me or contributor w/ 2nd status.io service at hand ;-)
Disclaimer: this is my first time touching base w/ Swift. You might want to extra carefully review ;-)
> added support for Docker

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Packet.swift
- stts/Services/Super/Service.swift
Added the status page for Packet
> Add Packet.net status

- stts/Services/StatusPage/Quay.swift
> Adding Quay.io

- stts/Services/StatusPage/Trello.swift
see: https://www.trellostatus.com/api
> [add] Trello

- stts/Services/StatusPage/Filestack.swift
source: https://status.filestack.com/api
> [add] Filestack

- stts/Services/StatusPage/Imgix.swift
I haven't tested this but seems fairly trivial to add new services based on StatusPage.
Great app 👍
> Add imgix status page

- stts/Services/StatusPage/Aptible.swift
source: http://status.aptible.com/api
> [add] Aptible

- stts/Services/StatusPage/Vimeo.swift
http://www.vimeostatus.com/api
> Adds Vimeo

- README.md
- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Spoke.swift
Status page for https://askspoke.com
> Add Spoke statuspage

- stts/Services/StatusPage/Robinhood.swift
> Adds Robinhood

- stts/Services/StatusPage/LastPass.swift
> Add LastPass

- stts.xcodeproj/project.pbxproj
- stts/Services/Avalara.swift
Adds support for Avalara's statuspage
> Add Avalara 

- stts.xcodeproj/project.pbxproj
- stts/Services/Recurly.swift
Adds support for Recurly's statuspage
> Add Recurly

- stts/Services/StatusPage/Asana.swift
Hello,
This PR add a service for Asana (https://app.asana.com/)
> Add Asana service

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Bitrise.swift
> Adding bitrise.io status page

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/ElasticCloud.swift
https://cloud-status.elastic.co/
> Add Elastic Cloud to StatusPage

- stts/Services/StatusPage/Egnyte.swift
Per your documentation I believe this is the appropriate way to add new services for display. Please review and if acceptable approve my pull request.
> Adding the status page checker for Egnyte from statuspage.io

- stts/Services/StatusPage/Box.swift
Adding a status option for Box as well.
> Add box status

- stts/Services/StatusPage/Fivetran.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/114)
> Add Statuspage for Fivetran

- stts/Services/StatusPage/Notion.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/116)
> Add Notion.so Statuspage

- stts/Services/StatusPage/Bitmovin.swift
Adds a new service definition for Bitmovin.
> Add Bitmovin status page

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Recruiterbox.swift
Adds [status page](https://status.recruiterbox.com) service for [Recruiterbox](https://recruiterbox.com) a applicant tracking system.
> Add Recruiterbox status page

- stts/Services/StatusPage/CoderPad.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/121)
> Add Statuspage for CoderPad

- stts/Services/StatusPage/Airbase.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/122)
> Add Statuspage for Airbase

- stts/Services/StatusPage/AuroraSolar.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/123)
> Add Statuspage for AuroraSolar

- stts/Services/StatusPage/Lever.swift
For reference: https://status.lever.co/api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/125)
> Add Lever.co

- stts/Services/StatusPage/BigCommerce.swift
Adding BigCommerce statuspage: https://status.bigcommerce.com/
> Add bigcommerce

- stts/Services/StatusPage/Poka.swift
Status page: https://www.pokastatus.io
Corporate page: https://www.poka.io
> Add Poka.io

- stts/Services/StatusPage/logzio.swift
this is the status oveview of service logz.io
> add logzio service

- stts/Services/StatusPage/AppCenter.swift
https://status.appcenter.ms/
https://status.appcenter.ms/api
> AppCenter Status Page Support

- stts/Services/StatusPage/ModeAnalytics.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inket/stts/136)
> Add Statuspage for Mode Analytics

- stts/Services/StatusPage/TwitchTV.swift
Reference:
https://status.twitch.tv
https://status.twitch.tv/api
> Add twitch status page

- stts/Services/StatusPage/Snowflake.swift
Reference:
https://status.snowflake.com/
https://status.snowflake.com/api
> Added service: Snowflake

- stts/Services/StatusPage/ReadMe.swift
Status page: https://www.readmestatus.com
Corporate page: https://readme.com
> Add Readme.com

- stts/Services/StatusPage/Acoustic.swift
- stts/Services/StatusPage/AlertLogic.swift
- stts/Services/StatusPage/JumpCloud.swift
Reference:
https://status.goacoustic.com/api
https://status.alertlogic.com/api
https://status.jumpcloud.com/api
> Added Acoustic, AlertLogic, and JumpCloud.

- Gemfile.lock
- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/HelloSignHelloFax.swift
> Add HelloSign / HelloFax status

- stts/Services/Status.ioV1/ClickUp.swift
@inket long time. 👋 
just started using this one.
> Adds ClickUp status

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Blend.swift
- stts/Services/StatusPage/Bugsnag.swift
- stts/Services/StatusPage/Customerio.swift
- stts/Services/StatusPage/Dialpad.swift
- stts/Services/StatusPage/Kustomer.swift
All use Atlassian Statuspage
- https://status.customerio.com/
- https://status.dialpad.com/
- https://status.kustomer.com/
- https://status.bugsnag.com/
- https://status.blend.com/
> Add services Blend, Bugsnag, Customerio, Dialpad, Kustomer

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/VMwareWorkspaceONE.swift
Generated with `bundle exec extract.rb https://status.workspaceone.com`
> Add VMware WorkspaceONE

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/VMwareCarbonBlack.swift
Add support for VMware's Carbon Black service: https://status.carbonblack.com/
> Add Support for VMware Carbon Black

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/TeleportCloud.swift
Teleport Cloud is a managed version of the OSS project https://github.com/gravitational/teleport
> Add support for teleport.sh cloud

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/SecurID.swift
Adds support for https://status.securid.com/
> Add RSA SecurID

- stts/Services/StatusPage/Shopify.swift
should be https://www.shopifystatus.com/
> Update Shopify.swift with correct status page

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Flyio.swift
Add support for hosting provider Fly.io status page. 
Closes #204
> add fly.io status page

- stts/Services/StatusPage/InternetComputer.swift
Add support for Internet Computer: decentralized cloud.
> Add support for Internet Computer

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/PlanningCenter.swift
Love this app.
Adding Planning Center, https://status.planningcenter.com/
```
❯ bundle exec ruby extract.rb https://status.planningcenter.com/
Updated stts/Services/StatusPage/PlanningCenter.swift
Added PlanningCenter.swift to project
Done!
Running synx...
```
> Service: Planning Center

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Productboard.swift
> Add Productboard status page

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Fleek.swift
> Add Fleek.xyz status page

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/AnthropicAI.swift
- stts/Services/StatusPage/DeepSeekAI.swift
Added:
- https://status.anthropic.com/
- https://status.deepseek.com/
> Adding AnthropicAI and DeepSeekAI

- stts.xcodeproj/project.pbxproj
- stts/Services/StatusPage/Wiz.swift
Adds status.wiz.io
```
$ bundle exec ruby extract.rb https://status.wiz.io/
Updated stts/Services/StatusPage/Wiz.swift
Added Wiz.swift to project
Done!
Running synx...
```
> Add status.wiz.io
